-- NIGRAANI: SQLite (demo.db) -> Supabase PostgreSQL schema.
-- Status: DRAFT FOR REVIEW. Not applied anywhere.
--
-- Mirrors backend/database.py init_db() so existing queries keep working:
--   * same table and column names (including the column named "timestamp")
--   * application-assigned IDs for users, orders and security_events
--   * generated IDs for detections and decisions ("by default" so the
--     transfer script can insert the original IDs, then advance the sequence)
--   * the partial unique indexes on analysis_key that make analyzer writes
--     idempotent
--
-- Deliberately no foreign keys on telemetry columns (security_events.user_id,
-- resource_id, resource_owner_id; detections.user_id). Enumeration and BOLA
-- traffic references IDs that do not exist (demo.db already holds 4 events
-- whose resource_id has no order), and a security logger must never drop an
-- event because of a constraint violation.
--
-- Fails if any table already exists (no IF NOT EXISTS) so it can't silently
-- merge with a half-built schema. Rollback: 001_nigraani_schema.down.sql.

begin;

set local search_path = public;

create table public.users (
    user_id bigint primary key,
    name    text not null,
    email   text not null
);

create table public.orders (
    order_id bigint primary key,
    owner_id bigint not null references public.users (user_id),
    product  text not null,
    amount   double precision not null
);

create index orders_owner_id_idx on public.orders (owner_id);

create table public.security_events (
    -- Assigned by backend/security_logger.py (epoch microseconds), exceeds int4.
    event_id          bigint primary key,
    "timestamp"       timestamptz not null,
    ip                text not null,
    user_id           bigint,
    method            text not null,
    endpoint          text not null,
    endpoint_pattern  text not null,
    resource_id       bigint,
    resource_owner_id bigint,
    status_code       integer not null,
    response_time_ms  double precision not null,
    sim_label         text not null default 'normal'
);

create index security_events_ip_idx on public.security_events (ip);
create index security_events_timestamp_idx on public.security_events ("timestamp");

create table public.detections (
    detection_id bigint generated by default as identity primary key,
    detector     text not null,
    attack_type  text not null,
    severity     integer not null,
    ip           text not null,
    user_id      bigint,
    evidence     text not null,
    event_ids    jsonb not null check (jsonb_typeof(event_ids) = 'array'),
    owasp        text not null default 'API1:2023',
    analysis_key text,
    -- Audit column. NULL for rows migrated from SQLite (original time unknown).
    created_at   timestamptz default now()
);

create unique index idx_detections_analysis_key
    on public.detections (analysis_key)
    where analysis_key is not null;
-- Serves the legacy-row lookup in insert_detection().
create index detections_legacy_lookup_idx
    on public.detections (detector, ip, attack_type, user_id)
    where analysis_key is null;
create index detections_ip_idx on public.detections (ip);
-- Lets investigate-style lookups use event_ids @> '[<id>]' instead of a scan.
create index detections_event_ids_gin on public.detections using gin (event_ids);

create table public.decisions (
    decision_id  bigint generated by default as identity primary key,
    ip           text not null,
    risk_score   integer not null,
    risk_level   text not null,
    action       text not null,
    reasons      jsonb not null check (jsonb_typeof(reasons) = 'array'),
    source       text not null default 'system',
    event_ids    jsonb check (event_ids is null or jsonb_typeof(event_ids) = 'array'),
    analysis_key text,
    created_at   timestamptz default now()
);

create unique index idx_decisions_analysis_key
    on public.decisions (analysis_key)
    where analysis_key is not null;
-- Serves investigate_event(): WHERE ip = ? ORDER BY decision_id.
create index decisions_ip_decision_id_idx on public.decisions (ip, decision_id);

-- RLS. The project's ensure_rls event trigger should already have done this,
-- but rls_auto_enable() swallows its own errors, so enable it explicitly.
-- No policies are created here: with RLS on and no policies, the Data API
-- roles (anon, authenticated) see nothing. Backend access is granted in
-- 003_app_role_policies.sql.
alter table public.users           enable row level security;
alter table public.orders          enable row level security;
alter table public.security_events enable row level security;
alter table public.detections      enable row level security;
alter table public.decisions       enable row level security;

-- Supabase default privileges grant these tables to the Data API roles.
-- Nothing in NIGRAANI reads Supabase directly (the frontend goes through
-- FastAPI), and users holds emails, so remove that exposure entirely.
revoke all on table
    public.users, public.orders, public.security_events,
    public.detections, public.decisions
from anon, authenticated;

comment on table public.security_events is 'NIGRAANI API telemetry (migrated from demo.db).';
comment on table public.detections is 'Detector findings. Append-only audit trail.';
comment on table public.decisions is 'Risk engine enforcement decisions. Append-only audit trail.';

commit;
